version: 2

builds:
  -
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

# The expected release workflow is to use the GitHub UI to create a new release
# (and tag) and manually curate the release notes.
release:
  mode: keep-existing

changelog:
  disable: true
